### ISSUE TITLE
About the Paper of GaitGraph2

### ISSUE THREAD

**Issue by HiAleeYang** [tteepe/GaitGraph2#1]
Thank you for your work in gait recognition. I have read your last paper GaitGraph. It really inspires me. I can't help but read your latest work in GaitGraph2.But I can not find the paper on the internet.
If possible, can you send me a copy of the paper? Or tell me how can I find it on the internet. I would appreciate it.

**Comment by tteepe** [comment]
Hi, thanks for your interest! 
It's now available on arXiv: https://arxiv.org/abs/2204.07855
