### ISSUE TITLE
Backbone mismatch between CASIA-B pre-trained model and model config.

### ISSUE THREAD

**Issue by khoapham2801** [tteepe/GaitGraph2#12]
@tteepe 
I faced an issue when trying to run predict on CASIA-B, there were many unexpected layers not recognized when loading `state_dict`.
The result of my investigation points out that there was a backend mismatch, more details below:

- In `casia_b.yaml`: `backend_name: resgcn-n21-r8`.
- However, the pre-trained model used backbone `resgcn-n31-r8` as stated in `hparams.yaml` and the training log file of this model as well. 
- There is no such `n31` structure defined in the `__init__.py` of ResGCNv1, thus changing the `backend_name` solves nothing.

**Comment by ramprabhakar** [comment]
Hi @khoapham2801, I am also facing the same issue. How did you solve this problem? Thanks!
