### ISSUE TITLE
Please share the ID_list.csv

### ISSUE THREAD

**Issue by ZhengLeon** [tteepe/GaitGraph2#2]
Hi @tteepe ,
Thanks for sharing this great job.
I can't find the ID_list.csv in OUMVLP-Pose dataset, could you please share it?

**Comment by tteepe** [comment]
Hi,
you can find the `ID_list.csv` on the website of [OUMVLP-Pose](http://www.am.sanken.osaka-u.ac.jp/BiometricDB/GaitLPPose.html):

[ID_list.csv (Subject List)](http://www.am.sanken.osaka-u.ac.jp/BiometricDB/dataset/GaitLPPose/ID_list.csv)
