### ISSUE TITLE
where can I find the checkpoint file ?

### ISSUE THREAD

**Issue by HiAleeYang** [tteepe/GaitGraph2#5]
Hi, I use the training command to finish the model train in caisa-b , but I can't find the checkpoint `--ckpt_path <path_to_checkpoint>` of the trained model when I do inference? Can you tell me where can I find the checkpoint file path or how to set the output checkpoint path?
Thank you very much!

**Comment by tteepe** [comment]
Hi, 
you can find the pre-trained checkpoints here:
https://github.com/tteepe/GaitGraph2/releases/tag/v0.1
